# Generated by Django 5.1.1 on 2024-10-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_alter_customuser_kurum"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboneTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255, verbose_name="Ad")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
            ],
            options={
                "verbose_name": "Abone Tip",
                "verbose_name_plural": "Abone Tipleri",
            },
        ),
        migrations.CreateModel(
            name="GelirTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255, verbose_name="Ad")),
                (
                    "muhasebe_kodu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Muhasebe Kodu",
                    ),
                ),
                (
                    "ekleyen",
                    models.IntegerField(
                        choices=[(1, "Sistem"), (2, "Kullanıcı")],
                        default=1,
                        verbose_name="Ekleyen",
                    ),
                ),
                (
                    "kurum_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Kurum ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gelir Tip",
                "verbose_name_plural": "Gelir Tipleri",
            },
        ),
        migrations.CreateModel(
            name="Mukellef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mukellef_no",
                    models.CharField(max_length=20, verbose_name="Mükellef No"),
                ),
                ("ad", models.CharField(max_length=255, verbose_name="Ad")),
                ("soyad", models.CharField(max_length=255, verbose_name="Soyad")),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="TC No"
                    ),
                ),
                (
                    "baba_ad",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Baba Adı"
                    ),
                ),
                (
                    "anne_ad",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Anne Adı"
                    ),
                ),
                (
                    "dogum_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "dogum_yeri",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Doğum Yeri"
                    ),
                ),
                (
                    "cinsiyet",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Erkek"), (2, "Kadın")],
                        null=True,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "medeni_durum",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Evli"),
                            (2, "Bekar"),
                            (3, "Dul"),
                            (4, "Boşanmış"),
                        ],
                        null=True,
                        verbose_name="Medeni Durum",
                    ),
                ),
                (
                    "egitim_durumu",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "İlkokul"),
                            (2, "Ortaokul"),
                            (3, "Lise"),
                            (4, "Önlisans"),
                            (5, "Lisans"),
                            (6, "Yüksek Lisans"),
                            (7, "Doktora"),
                        ],
                        null=True,
                        verbose_name="Eğitim Durumu",
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-Mail"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mukellefler",
                        to="account.kurum",
                        verbose_name="Kurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mükellef",
                "verbose_name_plural": "Mükellefler",
            },
        ),
        migrations.CreateModel(
            name="Abone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abone_no", models.CharField(max_length=20, verbose_name="Abone No")),
                ("ad", models.CharField(max_length=255, verbose_name="Ad")),
                ("soyad", models.CharField(max_length=255, verbose_name="Soyad")),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="TC No"
                    ),
                ),
                (
                    "baba_ad",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Baba Adı"
                    ),
                ),
                (
                    "anne_ad",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Anne Adı"
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "sayac_marka",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sayaç Marka",
                    ),
                ),
                (
                    "sayac_seri_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sayaç Seri No",
                    ),
                ),
                (
                    "sayac_durum",
                    models.IntegerField(
                        choices=[
                            (1, "Normal"),
                            (2, "Ters"),
                            (3, "Arızalı"),
                            (4, "Okunamıyor"),
                            (99, "Diğer"),
                        ],
                        default=1,
                        verbose_name="Sayaç Durum",
                    ),
                ),
                (
                    "endeks",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Sayaç endeksi. Sadece ilk kaydederken girilir.",
                        null=True,
                        verbose_name="Endeks",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aboneler",
                        to="account.kurum",
                        verbose_name="Kurum",
                    ),
                ),
                (
                    "abone_tip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aboneler",
                        to="gelir.abonetip",
                        verbose_name="Abone Tip",
                    ),
                ),
                (
                    "mukellef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aboneler",
                        to="gelir.mukellef",
                        verbose_name="Mükellef",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abone",
                "verbose_name_plural": "Aboneler",
            },
        ),
        migrations.CreateModel(
            name="SuTahakkuk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilk_endeks",
                    models.IntegerField(default=0, verbose_name="İlk Endeks"),
                ),
                (
                    "son_endeks",
                    models.IntegerField(default=0, verbose_name="Son Endeks"),
                ),
                ("tuketim", models.IntegerField(default=0, verbose_name="Tüketim")),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                ("tahakkuk_tarihi", models.DateField(verbose_name="Tahakkuk Tarihi")),
                (
                    "son_odeme_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Ödeme Tarihi"
                    ),
                ),
                (
                    "durum",
                    models.IntegerField(
                        choices=[
                            (1, "Beklemede"),
                            (2, "Ödendi"),
                            (3, "Parçalı Ödendi"),
                            (4, "İade"),
                            (5, "İptal"),
                            (99, "Diğer"),
                        ],
                        default=1,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "hesaplama",
                    models.TextField(blank=True, null=True, verbose_name="Hesaplama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "abone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tahakkuklar",
                        to="gelir.abone",
                        verbose_name="Abone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Su Tahakkuk",
                "verbose_name_plural": "Su Tahakkuklar",
            },
        ),
        migrations.CreateModel(
            name="SuTarife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilk_endeks",
                    models.IntegerField(default=0, verbose_name="İlk Endeks"),
                ),
                (
                    "son_endeks",
                    models.IntegerField(default=0, verbose_name="Son Endeks"),
                ),
                (
                    "tarife",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Tarife"
                    ),
                ),
                (
                    "abone_tip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifeler",
                        to="gelir.abonetip",
                        verbose_name="Abone Tip",
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifeler",
                        to="account.kurum",
                        verbose_name="Kurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Su Tarife",
                "verbose_name_plural": "Su Tarifeleri",
            },
        ),
        migrations.AddIndex(
            model_name="mukellef",
            index=models.Index(
                fields=["ad", "soyad"], name="gelir_mukel_ad_c847f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mukellef",
            index=models.Index(
                fields=["mukellef_no"], name="gelir_mukel_mukelle_d05c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abone",
            index=models.Index(
                fields=["ad", "soyad"], name="gelir_abone_ad_1cf6f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abone",
            index=models.Index(
                fields=["abone_no"], name="gelir_abone_abone_n_55b8aa_idx"
            ),
        ),
    ]
